### ISSUE TITLE
Recipient list doesn't respect multiple source folders

### ISSUE THREAD

**Issue by claude27** [jokumer/direct_mail#10]
When adding a second folder of tt_address addresses as source folder in a recipient list, only the first added folder is respected in the sending process (and counted in the overview in the menu "recipient list"). It seems not to make a difference if the folder is on the same page level as the first folder or if it is a sub folder of the first folder.

**Comment by jokumer** [comment]
Thx for reporting. Did you test it, if it work as expected in TYPO3 v8.7 with direct_mail v5.2.x?

**Comment by claude27** [comment]
thanks for your quick answer. Yes, it worked before. My client contacted me because the overall sum of sent emails was much lower than of the last newsletter which was sent with TYPO3 8.7 and direct_mail 5.23. I realized that the current number of recipients in the sending state (Versandstatus) module was exactly the number of addresses oft the first linked folder in the recipient list.

**Comment by jokumer** [comment]
Solved.
I have checked, and it is fixed with pull request https://github.com/kartolo/direct_mail/pull/169 by @vzz3 with comment: Fix compiling of Recipient List with "Include page subtree" enabled

This pull request is also merged into this fork version. See https://github.com/jokumer/direct_mail/commit/ed88594fb0565a05775a161cd71724902a098d66
