### ISSUE TITLE
DirectMailUtility->getUrlBase

### ISSUE THREAD

**Issue by bernd-reindl** [jokumer/direct_mail#16]
The function getFullUrlsForDirectMailRecord uses the function getUrlBase to fetch the base url, the plainTextUrl and the htmlUrl.

$row['page'] is the page in the default language. $row['HTMLParams'] and $row['plainParams'] contains the language param (e.g. &L=1). getUrlBase returns for htmlUrl the baseURL appended with the HTMLParams (e.g. www.test.at/test?&L=1

But in TYPO3 9.5 the language is part of the baseURL (e.g. www.test.at/en or en.test.at) configured in Sites module in the backend and not a parameter in the url. So fetching the content from an localized page fails.

I dont know if it´is helpful. But i have modified the getFullUrlsForDirectMailRecord function in a 5.x branch before to make it compatible with TYPO3 9.5. See attached code:
[directmail.txt](https://github.com/jokumer/direct_mail/files/4091785/directmail.txt)

**Comment by jokumer** [comment]
I haven't tested such case yet. I will check...

**Comment by thernst** [comment]
I have a similar issue. In my case I need to set the page type for the newsletter, so HTMLParams contains "?type=1234". Site config has a PageTypeRouteEnhancer for this page type. getUrlBase currently just adds the HTMLParams to the generated URL, so that it is not working.  I get the content for the default page type

However, I can confirm that the change from @bernd-reindl is working for my case as well.

**Comment by jokumer** [comment]
I have tested too and implemented code from @bernd-reindl. Thx for testing
